import type {Campaign,Mission} from '../shared/types';
const textFields:['name'|'title'|'relic'|'symbol'|'story'|'history'|'source'|'question'|'explanation'|'bonus',string][]=[['name','Lieu'],['title','Nom de l’épreuve'],['relic','Relique'],['symbol','Symbole'],['story','Archive fictive'],['history','Histoire du lieu'],['source','Source historique (HTTPS)'],['question','Énigme'],['explanation','Explication après résolution'],['bonus','Défi photo']];
export default function Editor({campaign,onChange,onSave,busy}:{campaign:Campaign;onChange:(c:Campaign)=>void;onSave:()=>void;busy:boolean}){
 const set=(k:keyof Campaign,v:any)=>onChange({...campaign,[k]:v});
 const edit=(i:number,k:keyof Mission,v:any)=>set('missions',campaign.missions.map((m,j)=>j===i?{...m,[k]:v}:m));
 return <section className="editor"><div className="section-heading"><div><p className="eyebrow">ATELIER D’ENQUÊTES</p><h2>Écrire les archives</h2></div><button className="primary" onClick={onSave} disabled={busy}>Enregistrer l’enquête</button></div><p className="muted">Une session conserve la version de l’enquête au moment de sa création. Chaque épreuve doit pouvoir être jouée dans n’importe quel ordre.</p>
 <div className="panel form-grid"><label>Titre<input value={campaign.title} onChange={e=>set('title',e.target.value)}/></label><label>Durée maximale (min)<input type="number" min="10" max="120" value={campaign.duration} onChange={e=>set('duration',+e.target.value)}/></label><label>Points par épreuve<input type="number" min="0" max="1000" value={campaign.points} onChange={e=>set('points',+e.target.value)}/></label><label>Pénalité par indice<input type="number" min="0" max="1000" value={campaign.hintPenalty} onChange={e=>set('hintPenalty',+e.target.value)}/></label><label className="wide">Introduction<textarea value={campaign.intro} onChange={e=>set('intro',e.target.value)}/></label></div>
 {campaign.missions.map((m,i)=><details className="panel" key={m.id}><summary><span className="rune">{m.symbol}</span> {i+1}. {m.name} <span className="muted">· {m.minutes} min · rayon {m.radius} m</span></summary><div className="form-grid editor-fields">{textFields.map(([k,label])=><label className={['story','history','question','bonus','explanation'].includes(k)?'wide':''} key={k}>{label}{['story','history','question','bonus','explanation'].includes(k)?<textarea value={m[k]} onChange={e=>edit(i,k,e.target.value)}/>:<input value={m[k]} onChange={e=>edit(i,k,e.target.value)}/>}</label>)}
 {([['lat','Latitude'],['lng','Longitude'],['radius','Rayon GPS (m)'],['minutes','Temps estimé (min)'],['bonusPoints','Bonus photo maximal']] as const).map(([k,l])=><label key={k}>{l}<input type="number" step={k==='lat'||k==='lng'?'0.000001':'1'} value={m[k]} onChange={e=>edit(i,k,+e.target.value)}/></label>)}
 <label className="wide">Réponses acceptées · une par ligne<textarea value={m.answers.join('\n')} onChange={e=>edit(i,'answers',e.target.value.split('\n'))}/></label><label className="wide">Choix affichés · un par ligne, vide pour saisie libre<textarea value={m.options.join('\n')} onChange={e=>edit(i,'options',e.target.value?e.target.value.split('\n'):[])}/></label><label className="wide">Indices progressifs · un par ligne<textarea value={m.hints.join('\n')} onChange={e=>edit(i,'hints',e.target.value?e.target.value.split('\n'):[])}/></label></div><button className="danger" disabled={campaign.missions.length<=1} onClick={()=>set('missions',campaign.missions.filter((_,j)=>i!==j))}>Retirer cette épreuve</button></details>)}
 <button onClick={()=>{const m=campaign.missions[0];set('missions',[...campaign.missions,{...m,id:'epreuve-'+crypto.randomUUID().slice(0,8),name:'Nouveau lieu',title:'Nouvelle épreuve',question:'Votre énigme',answers:['réponse'],hints:['Votre indice'],options:[]}])}} disabled={campaign.missions.length>=20||!campaign.missions.length}>Ajouter une épreuve</button>
 <div className="panel form-grid"><h3 className="wide">Rituel final</h3><label className="wide">Question<textarea value={campaign.finale.question} onChange={e=>set('finale',{...campaign.finale,question:e.target.value})}/></label><label className="wide">Choix · un par ligne<textarea value={campaign.finale.options.join('\n')} onChange={e=>set('finale',{...campaign.finale,options:e.target.value?e.target.value.split('\n'):[]})}/></label><label>Réponse exacte<input value={campaign.finale.answer} onChange={e=>set('finale',{...campaign.finale,answer:e.target.value})}/></label><label>Points<input type="number" value={campaign.finale.points} onChange={e=>set('finale',{...campaign.finale,points:+e.target.value})}/></label><label className="wide">Conclusion<textarea value={campaign.finale.explanation} onChange={e=>set('finale',{...campaign.finale,explanation:e.target.value})}/></label></div><button className="primary" onClick={onSave} disabled={busy}>Enregistrer l’enquête</button></section>
}
