import {useEffect,useRef} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import type {Mission,Team,Point} from '../shared/types';
export default function FieldMap({missions,teams=[],position,onSelect,tracks=[]}:{missions:Mission[];teams?:Team[];position?:Point|null;onSelect:(id:string)=>void;tracks?:any[]}){
 const el=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),layer=useRef<L.LayerGroup|null>(null),select=useRef(onSelect);select.current=onSelect;
 useEffect(()=>{if(!el.current)return;const m=L.map(el.current,{zoomControl:false}).setView([48.8907,2.2426],16);map.current=m;L.control.zoom({position:'bottomright'}).addTo(m);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(m);layer.current=L.layerGroup().addTo(m);const ro=new ResizeObserver(()=>m.invalidateSize());ro.observe(el.current);return()=>{ro.disconnect();m.remove();map.current=null}},[]);
 useEffect(()=>{const m=map.current,g=layer.current;if(!m||!g)return;g.clearLayers();missions.forEach((p,i)=>{L.circle([p.lat,p.lng],{radius:p.radius,color:'#cda567',weight:1,fillOpacity:.12}).addTo(g);const icon=L.divIcon({className:'map-rune',html:`<span>${i+1}</span>`,iconSize:[34,34],iconAnchor:[17,17]});L.marker([p.lat,p.lng],{icon,title:p.name,keyboard:true}).on('click',()=>select.current(p.id)).addTo(g)});teams.forEach(t=>{if(t.lat===null||t.lng===null)return;const old=Date.now()-(t.located_at||0)>45000;const marker=L.circleMarker([t.lat,t.lng],{radius:7,color:old?'#819095':'#83c7b4',fillColor:old?'#819095':'#83c7b4',fillOpacity:1});const label=document.createElement('span');label.textContent=`${t.name}${old?' · ancienne position':''}`;marker.bindTooltip(label).addTo(g)});if(position)L.circleMarker([position.lat,position.lng],{radius:6,color:'#fff',fillColor:'#70bba7',fillOpacity:1,weight:3}).addTo(g);const grouped=new Map<string,[number,number][]>();[...tracks].reverse().forEach(p=>{const points=grouped.get(p.team_id)||[];points.push([+p.lat,+p.lng]);grouped.set(p.team_id,points)});grouped.forEach(points=>L.polyline(points,{color:'#70bba7',weight:2,opacity:.5}).addTo(g));},[missions,teams,position,tracks]);
 useEffect(()=>{if(missions.length&&map.current){map.current.fitBounds(L.latLngBounds(missions.map(m=>[m.lat,m.lng])),{padding:[35,35],maxZoom:16})}},[missions.map(m=>m.id+':'+m.lat+':'+m.lng).join('|')]);
 return <div className="field-map" ref={el} role="region" aria-label="Carte des épreuves et des équipes"/>;
}
