import {Miniflare} from 'miniflare';
import {readFile,readdir,mkdir,rm} from 'node:fs/promises';
import assert from 'node:assert/strict';
const persist='.sites-runtime/flow-test';await rm(persist,{recursive:true,force:true});await mkdir(persist,{recursive:true});
const config={modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2026-07-30',d1Databases:{DB:'reliquaire-test'},r2Buckets:['BUCKET'],d1Persist:persist+'/db',r2Persist:persist+'/r2'};
let mf=new Miniflare(config),db=await mf.getD1Database('DB');
for(const name of (await readdir('drizzle')).filter(v=>v.endsWith('.sql')).sort())for(const sql of (await readFile('drizzle/'+name,'utf8')).split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql).run();
let checks=0;
async function call(path,body,token='',who='',expect=200){const r=await mf.dispatchFetch('https://test.invalid'+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{'X-Team-Token':token}:{}),...(who?{'oai-authenticated-user-id':who}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert.equal(r.status,expect,JSON.stringify(data));checks++;return data}
const p='/api/reliquaire';
await call(p+'/admin',null,'','',401);
const admin=await call(p+'/admin',null,'','owner');const campaign=admin.campaigns[0].data;
assert.equal(campaign.missions.length,6);assert.equal(campaign.duration,120);
const c=await call(p+'/catalog');assert.deepEqual(c.campaign.missions[0].answers,[]);assert.equal(c.campaign.finale.answer,'');
const {code}=await call(p+'/sessions',{name:'Integration screen',mode:'screen',duration:120,campaign},'','owner',201);
const root=p+'/s/'+code;const edited=structuredClone(campaign);edited.title='Enquête modifiée';const saved=await call(p+'/campaigns',{id:'default',campaign:edited},'','owner');assert.ok(saved.id);await call(p+'/campaigns',{id:saved.id,campaign:edited},'','other',404);const frozen=await call(root);assert.equal(frozen.session.campaign.title,campaign.title);
const alice=await call(root+'/teams',{name:'Archivistes',members:['Alice','Bob']},'','',201);
const bob=await call(root+'/teams',{name:'Veilleurs',members:['Chloé']},'','',201);
await call(root+'/puzzle',{mission:'arche',action:'answer',answer:'200'},alice.token,'',409);
await call(root+'/control',{action:'start'},alice.token,'',403);
await call(root+'/control',{action:'start'},'','other',403);
await call(root+'/control',{action:'start'},'','owner');
await call(root+'/puzzle',{mission:'arche',action:'open'},alice.token);
await call(root+'/puzzle',{mission:'arche',action:'hint'},alice.token);
const wrong=await call(root+'/puzzle',{mission:'arche',action:'answer',answer:'wrong'},alice.token);assert.equal(wrong.correct,false);
await call(root+'/puzzle',{mission:'arche',action:'open'},alice.token,'',409);
await call(root+'/puzzle',{mission:'arche',action:'answer',answer:'200'},alice.token,'',409);
let team=await db.prepare('SELECT state FROM r_teams WHERE id = ?').bind(alice.id).first();let st=JSON.parse(team.state);st.progress[0].cooldown_until=Date.now()-1;await db.prepare('UPDATE r_teams SET state = ? WHERE id = ?').bind(JSON.stringify(st),alice.id).run();
const solved=await call(root+'/puzzle',{mission:'arche',action:'answer',answer:' 200 ANS '},alice.token);assert.equal(solved.points,80);
await call(root+'/puzzle',{mission:'arche',action:'answer',answer:'200'},alice.token,'',409);
await call(root+'/puzzle',{mission:'takis',action:'skip'},alice.token);
let snap=await call(root,null,alice.token);let me=snap.teams.find(t=>t.id===alice.id);assert.equal(me.score,80);assert.equal(me.penalty,15);assert.equal(me.progress.find(p=>p.mission_id==='takis').status,'skipped');assert.equal(me.progress.find(p=>p.mission_id==='takis').points,0);assert.deepEqual(snap.session.campaign.missions[1].answers,[]);assert.equal(snap.teams.find(t=>t.id===bob.id).members.length,0);
await call(root+'/puzzle',{mission:'takis',action:'hint'},alice.token,'',409);
await call(root+'/finale',{answer:campaign.finale.answer},alice.token,'',400);
await call(root+'/messages',{body:'Besoin d’aide'},alice.token);
await call(root+'/messages',{channel:'all',body:'Une annonce'},'','owner');
await call(root+'/messages',{channel:'team',team:alice.id,body:'Conseil privé'},'','owner');
const bobSnap=await call(root,null,bob.token);assert.deepEqual(bobSnap.messages.map(m=>m.body),['Une annonce']);
const recovery=await call(root+'/resume',{team:alice.id,recovery:alice.recovery});
await call(root+'/puzzle',{mission:'pouce',action:'open'},alice.token,'',401);alice.token=recovery.token;
await call(root+'/roster',{members:['Alice','Bob','Dana']},alice.token);
for(const m of campaign.missions.filter(m=>!['arche','takis'].includes(m.id)))await call(root+'/puzzle',{mission:m.id,action:'answer',answer:m.answers[0]},alice.token);
await call(root+'/finale',{answer:campaign.finale.answer},alice.token);
snap=await call(root,null,alice.token);me=snap.teams.find(t=>t.id===alice.id);assert.equal(me.score,680);assert.equal(me.progress.length,6);assert.ok(me.finished_at);
await call(root+'/metrics',{steps:42},alice.token);
await call(root+'/metrics',{steps:20},alice.token);
const frozenElapsed=me.elapsed;await call(root+'/control',{action:'pause'},'','owner');const pausedSnapshot=await call(root,null,alice.token);assert.equal(pausedSnapshot.teams.find(t=>t.id===alice.id).elapsed,frozenElapsed);await call(root+'/puzzle',{mission:'arche',action:'open'},bob.token,'',409);await call(root+'/control',{action:'resume'},'','owner');
const terrain=await call(p+'/sessions',{name:'Terrain',mode:'terrain',duration:120,campaign},'','owner',201);const tr=p+'/s/'+terrain.code;const walker=await call(tr+'/teams',{name:'Piétons',members:['Eve']},'','',201);await call(tr+'/control',{action:'start'},'','owner');await call(tr+'/puzzle',{mission:'arche',action:'open'},walker.token,'',409);
await call(tr+'/location',{lat:48,lng:2,accuracy:10},walker.token);await call(tr+'/puzzle',{mission:'arche',action:'open'},walker.token,'',409);
await call(tr+'/location',{lat:campaign.missions[0].lat,lng:campaign.missions[0].lng,accuracy:400},walker.token);await call(tr+'/puzzle',{mission:'arche',action:'open'},walker.token,'',409);
await call(tr+'/location',{lat:campaign.missions[0].lat,lng:campaign.missions[0].lng,accuracy:10},walker.token);await call(tr+'/puzzle',{mission:'arche',action:'open'},walker.token);
await call(tr+'/location',{lat:48,lng:2,accuracy:10},walker.token);await call(tr+'/puzzle',{mission:'arche',action:'answer',answer:'200'},walker.token,'',409);await call(tr+'/intervention',{team:walker.id,mission:'arche',action:'bypass'},'','owner');await call(tr+'/puzzle',{mission:'arche',action:'answer',answer:'200'},walker.token);
// Upload actual tiny PNG, validate bonus, ensure other team's access only at closure.
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64');const f=new FormData();f.set('mission','arche');f.set('caption','Le selfie du seuil');f.set('file',new File([png],'photo.png',{type:'image/png'}));
const encoded=new Request('https://test.invalid'+root+'/photos',{method:'POST',body:f});const upload=await mf.dispatchFetch(encoded.url,{method:'POST',headers:{...Object.fromEntries(encoded.headers),'X-Team-Token':alice.token},body:await encoded.arrayBuffer()});assert.equal(upload.status,201,await upload.clone().text());const photo=await upload.json();checks++;
let image=await mf.dispatchFetch('https://test.invalid'+root+'/photos/'+photo.id,{headers:{'X-Team-Token':bob.token}});assert.equal(image.status,403);
await call(root+'/review',{photo:photo.id,points:30},'','owner');snap=await call(root,null,alice.token);assert.equal(snap.teams.find(t=>t.id===alice.id).score,710);
await call(root+'/control',{action:'end'},'','owner');image=await mf.dispatchFetch('https://test.invalid'+root+'/photos/'+photo.id,{headers:{'X-Team-Token':bob.token}});assert.equal(image.status,200);assert.equal((await image.arrayBuffer()).byteLength,png.length);
const exported=await call(tr+'/export',null,'','owner');assert.equal(exported.locations.length,4);assert.ok(exported.events.some(e=>e.kind==='intervention'));
// Persistent records and R2 object survive worker destruction/recreation.
await mf.dispose();mf=new Miniflare(config);db=await mf.getD1Database('DB');snap=await call(root,null,alice.token);me=snap.teams.find(t=>t.id===alice.id);assert.equal(me.score,710);assert.equal(me.steps,42);assert.equal(me.members.length,3);assert.equal(snap.session.status,'ended');assert.equal(snap.photos.length,1);assert.ok(snap.messages.some(m=>m.body==='Conseil privé'));
image=await mf.dispatchFetch('https://test.invalid'+root+'/photos/'+photo.id,{headers:{'X-Team-Token':alice.token}});assert.equal(image.status,200);
const home=await mf.dispatchFetch('https://test.invalid/');assert.equal(home.status,200);assert.ok((await home.text()).includes('Le Reliquaire'));const game=await mf.dispatchFetch('https://test.invalid/reliquaire/');assert.equal(game.status,200);assert.ok((await game.text()).includes('Le Reliquaire'));
await mf.dispose();console.log(`PASS: ${checks} API checks, GPS zones, cooldown, hints, skip, finale, authorization, private messages, captain recovery, R2 photos, ranking, persistent restart, standalone home served.`);
