import { campaign as defaultCampaign } from '../shared/campaign';
import { distance,inZone,normalize,missionPoints,sortTeams } from '../shared/rules';
import type {Campaign,Progress,Team} from '../shared/types';
type Env={DB:any;BUCKET:any};
type State={progress:Progress[];final_status:string;final_points:number;final_errors:number;final_cooldown:number;finished_at:number|null;elapsed_ms?:number;bypass:string[]};
class Failure extends Error {constructor(message:string,public status=400){super(message)}}
function fail(m:string,s=400):never {throw new Failure(m,s)}
const j=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const uid=()=>crypto.randomUUID();
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(8)),n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%32]).join('');
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');
const owner=(r:Request)=>r.headers.get('oai-authenticated-user-id')||fail('Ouvre le site avec ton compte pour accéder au maître de jeu.',401);
const str=(v:any,max=120)=>typeof v==='string'&&v.trim()&&v.trim().length<=max?v.trim():fail('Vérifie les champs du formulaire.');
const num=(v:any,a:number,b:number)=>typeof v==='number'&&Number.isFinite(v)&&v>=a&&v<=b?v:fail('Valeur numérique invalide.');
const all=async(db:any,sql:string,...args:any[])=>(await db.prepare(sql).bind(...args).all()).results;
const one=async(db:any,sql:string,...args:any[])=>(await all(db,sql,...args))[0];
const stmt=(db:any,sql:string,...args:any[])=>db.prepare(sql).bind(...args);
const parse=(s:string)=>JSON.parse(s);
async function body(r:Request){if(!r.headers.get('Content-Type')?.startsWith('application/json'))fail('Format JSON attendu.',415);const t=await r.text();if(t.length>150000)fail('Formulaire trop volumineux.',413);try{const value=JSON.parse(t);if(!value||typeof value!=='object'||Array.isArray(value))fail('Formulaire invalide.');return value}catch{fail('Formulaire invalide.')}}
function validateCampaign(c:Campaign){
 if(!c||typeof c!=='object'||Array.isArray(c)||!c.finale||typeof c.finale!=='object')fail('Enquête invalide.');
 str(c.title);str(c.intro,5000);num(c.duration,10,120);num(c.points,0,1000);num(c.hintPenalty,0,1000);
 if(!Array.isArray(c.missions)||!c.missions.length||c.missions.length>20)fail('Prévois de 1 à 20 épreuves.');
 const ids=new Set();for(const m of c.missions){if(!m||typeof m!=='object')fail('Épreuve invalide.');for(const key of ['answers','hints','options'] as const){if(Array.isArray(m[key]))m[key]=m[key].map(v=>typeof v==='string'?v.trim():v).filter(v=>v!=='')}str(m.id,60);if(!/^[a-z0-9-]+$/.test(m.id)||ids.has(m.id))fail('Identifiants des épreuves invalides ou dupliqués.');ids.add(m.id);str(m.name);str(m.title);str(m.relic);str(m.symbol,10);str(m.story,5000);str(m.history,3000);str(m.question,3000);str(m.explanation,3000);str(m.bonus,1000);num(m.lat,-90,90);num(m.lng,-180,180);num(m.radius,20,500);num(m.minutes,1,40);num(m.bonusPoints,0,500);if(!Array.isArray(m.answers)||!m.answers.length||m.answers.length>10)fail('Ajoute une réponse par épreuve.');m.answers.forEach(v=>str(v,500));if(!Array.isArray(m.hints)||m.hints.length>5||!Array.isArray(m.options)||m.options.length>8)fail('Trop d’indices ou de choix.');m.hints.forEach(v=>str(v,1000));m.options.forEach(v=>str(v,500));if(m.source){try{if(new URL(m.source).protocol!=='https:')fail('Source HTTPS attendue.')}catch{fail('Lien de source invalide.')}}}
 str(c.finale.question,3000);str(c.finale.answer,500);str(c.finale.explanation,3000);num(c.finale.points,0,1000);if(!Array.isArray(c.finale.options)||c.finale.options.length>8)fail('Choix de finale invalides.');c.finale.options.forEach(v=>str(v,500));return c;
}
function clean(c:Campaign):Campaign{return {...c,missions:c.missions.map(m=>({...m,answers:[],hints:m.hints.map(()=>''),explanation:''})),finale:{...c.finale,answer:'',explanation:''}}}
const initial=(c:Campaign):State=>({progress:c.missions.map(m=>({mission_id:m.id,status:'pending',hints:0,errors:0,points:0,cooldown_until:0,completed_at:null,opened_at:null})),final_status:'pending',final_points:0,final_errors:0,final_cooldown:0,finished_at:null,bypass:[]});
const remaining=(s:any,now:number)=>s.status==='lobby'?s.duration*60:s.status==='paused'?Math.max(0,Math.ceil((s.deadline-s.paused_at)/1000)):Math.max(0,Math.ceil(((s.deadline||now)-now)/1000));
async function session(db:any,code:string){const s=await one(db,'SELECT * FROM r_sessions WHERE code = ?',code.toUpperCase());if(!s)fail('Session introuvable. Vérifie le code.',404);return s}
function running(s:any){if(s.status!=='running')fail(s.status==='paused'?'La session est en pause.':s.status==='lobby'?'Le maître de jeu n’a pas encore donné le départ.':'La session est terminée.',409);if(Date.now()>=s.deadline)fail('Le temps est écoulé.',409)}
async function auth(r:Request,db:any,s:any){const user=r.headers.get('oai-authenticated-user-id');const admin=!!user&&s.owner_id===user;const token=r.headers.get('X-Team-Token');const t=token?await one(db,'SELECT * FROM r_teams WHERE session_id = ? AND token_hash = ?',s.id,await hash(token)):null;return {admin,t}}
async function event(db:any,s:any,t:any,kind:string,detail:string){await stmt(db,'INSERT INTO r_events (id,session_id,team_id,kind,detail,created_at) VALUES (?,?,?,?,?,?)',uid(),s.id,t?.id||null,kind,detail,Date.now()).run()}
function zone(s:any,t:any,m:any,state:State){if(s.mode==='screen'||state.bypass.includes(m.id))return;if(t.lat===null||Date.now()-t.located_at>45000||!inZone({lat:+t.lat,lng:+t.lng},m,+t.accuracy))fail('Approche du cercle GPS de cette épreuve. Une position récente et précise est nécessaire.',409)}
async function mutate(db:any,t:any,fn:(state:State)=>void){for(let attempt=0;attempt<3;attempt++){const current=await one(db,'SELECT * FROM r_teams WHERE id = ?',t.id);const state:State=parse(current.state);fn(state);const r=await stmt(db,'UPDATE r_teams SET state = ?, version = version + 1 WHERE id = ? AND version = ?',JSON.stringify(state),t.id,current.version).run();if(r.meta.changes)return state;}fail('Une action simultanée a eu lieu. Réessaie.',409)}
async function snapshot(r:Request,env:Env,s:any){
 const db=env.DB,now=Date.now();if(s.status==='running'&&now>=s.deadline){await stmt(db,"UPDATE r_sessions SET status = 'ended' WHERE id = ? AND status = 'running' AND deadline <= ?",s.id,now).run();s={...s,status:'ended'}}
 const {admin,t}=await auth(r,db,s),c:Campaign=parse(s.campaign);
 const [rows,messages,photos,events]=await Promise.all([
 all(db,'SELECT * FROM r_teams WHERE session_id = ? ORDER BY created_at',s.id),
 (admin||t)?all(db,`SELECT * FROM r_messages WHERE session_id = ? ${admin?'':"AND (channel = 'all' OR team_id = ?)"} ORDER BY created_at DESC LIMIT 100`,s.id,...(admin?[]:[t.id])):[],
 (admin||t)?all(db,`SELECT p.*, t.name AS team_name FROM r_photos p JOIN r_teams t ON t.id = p.team_id WHERE p.session_id = ? ${admin||s.status==='ended'?'':'AND p.team_id = ?'} ORDER BY p.created_at DESC`,s.id,...(admin||s.status==='ended'?[]:[t.id])):[],
 admin?all(db,'SELECT e.*, t.name AS team_name FROM r_events e LEFT JOIN r_teams t ON t.id = e.team_id WHERE e.session_id = ? ORDER BY e.created_at DESC LIMIT 250',s.id):[]
 ]);
 // Photo scores are included independently of the gallery's visibility.
 const bonuses=await all(db,'SELECT team_id, SUM(points) AS points FROM r_photos WHERE session_id = ? GROUP BY team_id',s.id);
 const teams=rows.map((row:any)=>{const state:State=parse(row.state),mine=t?.id===row.id;const progress=state.progress.map(p=>({...p,revealedHints:mine||admin?c.missions.find(m=>m.id===p.mission_id)!.hints.slice(0,p.hints):[],explanation:(mine||admin)&&p.status!=='pending'?c.missions.find(m=>m.id===p.mission_id)!.explanation:''}));const bonus=bonuses.find((x:any)=>x.team_id===row.id)?.points||0;const end=state.finished_at|| (s.status==='ended'?Math.min(now,s.deadline||now):now);const elapsed=state.finished_at&&state.elapsed_ms!==undefined?state.elapsed_ms:s.started_at?Math.max(0,end-s.started_at-s.paused_ms-(s.status==='paused'?now-s.paused_at:0)):0;
 return {id:row.id,name:row.name,members:admin||mine?parse(row.members):[],member_count:parse(row.members).length,score:progress.reduce((v,p)=>v+p.points,0)+state.final_points+bonus,penalty:(progress.reduce((v,p)=>v+p.errors,0)+state.final_errors)*15,lat:admin||t?(row.lat===null?null:+row.lat):null,lng:admin||t?(row.lng===null?null:+row.lng):null,accuracy:row.accuracy===null?null:+row.accuracy,located_at:row.located_at,distance:row.distance,steps:admin||mine?row.steps:0,steps_supported:row.steps_supported,finished_at:state.finished_at,progress,bonus,final_points:state.final_points,final_status:state.final_status,final_cooldown:state.final_cooldown,final_explanation:state.final_status==='solved'&&(mine||admin)?c.finale.explanation:'',elapsed};});
 const {owner_id,campaign,...publicSession}=s;return j({session:{...publicSession,campaign:admin?c:clean(c),remaining:remaining(s,now)},teams:sortTeams(teams as Team[]),messages:messages.reverse(),photos:photos.map((p:any)=>{const {object_key,...rest}=p;return {...rest,url:`/api/reliquaire/s/${s.code}/photos/${p.id}`}}),events,mine:t?.id||null,role:admin?'admin':t?'captain':'guest',serverNow:now});
}
export async function reliquaireApi(r:Request,env:Env){try{
 const db=env.DB;if(!db)fail('La sauvegarde est momentanément indisponible.',503);const url=new URL(r.url),path=url.pathname.slice('/api/reliquaire'.length);
 if(!['GET','HEAD'].includes(r.method)){if((r.headers.get('Origin')&&r.headers.get('Origin')!==url.origin)||r.headers.get('Sec-Fetch-Site')==='cross-site')fail('Requête externe refusée.',403)}
 if(path==='/catalog'&&r.method==='GET')return j({campaign:clean(defaultCampaign)});
 if(path==='/admin'&&r.method==='GET'){const user=owner(r);const [cs,ss]=await Promise.all([all(db,'SELECT * FROM r_campaigns WHERE owner_id = ? ORDER BY updated_at DESC',user),all(db,'SELECT id,code,name,status,mode,created_at FROM r_sessions WHERE owner_id = ? ORDER BY created_at DESC LIMIT 100',user)]);return j({campaigns:cs.length?cs.map((v:any)=>({id:v.id,data:parse(v.data)})):[{id:'default',data:defaultCampaign}],sessions:ss})}
 if(path==='/campaigns'&&r.method==='POST'){const user=owner(r),b=await body(r),c=validateCampaign(b.campaign);let id=b.id;if(!id||id==='default')id=uid();else if(!(await one(db,'SELECT id FROM r_campaigns WHERE id = ? AND owner_id = ?',id,user)))fail('Enquête introuvable.',404);await stmt(db,'INSERT INTO r_campaigns (id,owner_id,data,updated_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET data = excluded.data, updated_at = excluded.updated_at',id,user,JSON.stringify(c),Date.now()).run();return j({id,campaign:c})}
 if(path==='/sessions'&&r.method==='POST'){const user=owner(r),b=await body(r);const c=validateCampaign(b.campaign||defaultCampaign),duration=num(b.duration??c.duration,10,120),mode=b.mode==='screen'?'screen':'terrain',id=uid(),code=random(),now=Date.now();await stmt(db,'INSERT INTO r_sessions (id,owner_id,code,name,mode,status,duration,campaign,created_at) VALUES (?,?,?,?,?,?,?,?,?)',id,user,code,str(b.name),mode,'lobby',duration,JSON.stringify(c),now).run();return j({code,id},201)}
 const match=path.match(/^\/s\/([A-Z0-9]{8})(?:\/(.*))?$/i);if(!match)fail('Adresse inconnue.',404);
 const s=await session(db,match[1]),action=match[2]||'';
 if(!action&&r.method==='GET')return snapshot(r,env,s);
 const {admin,t}=await auth(r,db,s),c:Campaign=parse(s.campaign);
 if(action==='teams'&&r.method==='POST'){
  if(!['lobby','running'].includes(s.status)||s.deadline&&s.deadline<Date.now())fail('Les inscriptions sont fermées.',409);
  const b=await body(r),name=str(b.name,60),members=Array.isArray(b.members)?b.members.map((v:any)=>str(v,60)):fail('Ajoute au moins un membre.');if(!members.length||members.length>12)fail('Prévois de 1 à 12 membres.');
  const count=await one(db,'SELECT COUNT(*) AS n FROM r_teams WHERE session_id = ?',s.id);if(count.n>=50)fail('Cette session accueille déjà 50 équipes.');if(await one(db,'SELECT id FROM r_teams WHERE session_id = ? AND lower(name) = lower(?)',s.id,name))fail('Ce nom d’équipe est déjà utilisé.');
  const id=uid(),token=uid()+uid(),recovery=random()+random();await stmt(db,'INSERT INTO r_teams (id,session_id,name,members,token_hash,recovery_hash,state,created_at) VALUES (?,?,?,?,?,?,?,?)',id,s.id,name,JSON.stringify(members),await hash(token),await hash(recovery),JSON.stringify(initial(c)),Date.now()).run();await event(db,s,{id},'équipe',`${name} rejoint la session.`);return j({id,token,recovery},201)
 }
 if(action==='resume'&&r.method==='POST'){const b=await body(r);const row=await one(db,'SELECT * FROM r_teams WHERE session_id = ? AND id = ? AND recovery_hash = ?',s.id,str(b.team),await hash(str(b.recovery,40).toUpperCase().replace(/\s/g,'')));if(!row)fail('Code de reprise incorrect.',403);const token=uid()+uid();await stmt(db,'UPDATE r_teams SET token_hash = ? WHERE id = ?',await hash(token),row.id).run();return j({id:row.id,token})}
 if(action==='control'&&r.method==='POST'){
  if(!admin)fail('Accès maître de jeu requis.',403);const b=await body(r),now=Date.now();let q;
  if(b.action==='start'&&s.status==='lobby')q=stmt(db,"UPDATE r_sessions SET status = 'running', started_at = ?, deadline = ? WHERE id = ? AND status = 'lobby'",now,now+s.duration*60000,s.id);
  else if(b.action==='pause'&&s.status==='running'&&now<s.deadline)q=stmt(db,"UPDATE r_sessions SET status = 'paused', paused_at = ? WHERE id = ? AND status = 'running'",now,s.id);
  else if(b.action==='resume'&&s.status==='paused')q=stmt(db,"UPDATE r_sessions SET status = 'running', deadline = deadline + ?, paused_ms = paused_ms + ?, paused_at = NULL WHERE id = ? AND status = 'paused'",now-s.paused_at,now-s.paused_at,s.id);
  else if(b.action==='end'&&s.status!=='ended')q=stmt(db,"UPDATE r_sessions SET status = 'ended', deadline = ?, paused_ms = paused_ms + ?, paused_at = NULL WHERE id = ?",s.status==='paused'?now:Math.min(now,s.deadline||now),s.status==='paused'?now-s.paused_at:0,s.id);
  else fail('Cette action n’est pas disponible.',409);await q.run();await event(db,s,null,'session',b.action);return j({ok:true});
 }
 if(action==='roster'&&r.method==='POST'){if(!t)fail('Reprends ton équipe.',401);const b=await body(r);if(!Array.isArray(b.members)||!b.members.length||b.members.length>12)fail('Prévois de 1 à 12 membres.');const members=b.members.map((v:any)=>str(v,60));await stmt(db,'UPDATE r_teams SET members = ? WHERE id = ?',JSON.stringify(members),t.id).run();return j({ok:true})}
 if(action==='metrics'&&r.method==='POST'){if(!t)fail('Reprends ton équipe.',401);running(s);const b=await body(r);const steps=Math.max(t.steps,Math.floor(num(b.steps,0,2000000)));await stmt(db,'UPDATE r_teams SET steps = ?, steps_supported = 1 WHERE id = ?',steps,t.id).run();return j({ok:true})}
 if(action==='location'&&r.method==='POST'){
  if(!t)fail('Reprends ton équipe.',401);running(s);const b=await body(r),lat=num(b.lat,-90,90),lng=num(b.lng,-180,180),accuracy=num(b.accuracy,0,10000),now=Date.now();
  const d=t.lat!==null&&now-t.located_at<=60000&&accuracy<=100&&+t.accuracy<=100?distance({lat:+t.lat,lng:+t.lng},{lat,lng}):0;const dt=(now-(t.located_at||now))/1000,increment=dt>=3&&d/dt<=8&&d>Math.max(4,Math.min(accuracy,+t.accuracy)/2)?Math.round(d):0;
  const steps=b.steps===undefined?t.steps:Math.max(t.steps,Math.floor(num(b.steps,0,2000000)));await db.batch([stmt(db,'UPDATE r_teams SET lat = ?, lng = ?, accuracy = ?, located_at = ?, distance = distance + ?, steps = ?, steps_supported = ? WHERE id = ?',String(lat),String(lng),String(accuracy),now,increment,steps,b.stepsSupported?1:t.steps_supported,t.id),stmt(db,'INSERT INTO r_locations (id,session_id,team_id,lat,lng,accuracy,created_at) VALUES (?,?,?,?,?,?,?)',uid(),s.id,t.id,String(lat),String(lng),String(accuracy),now)]);return j({ok:true,at:now})
 }
 if(action==='puzzle'&&r.method==='POST'){
  if(!t)fail('Reprends ton équipe.',401);running(s);const b=await body(r),m=c.missions.find(v=>v.id===b.mission);if(!m)fail('Épreuve inconnue.');let result:any={};const now=Date.now();
  await mutate(db,t,state=>{const p=state.progress.find(v=>v.mission_id===m.id)!;if(p.status!=='pending')fail('Cette relique est déjà obtenue.',409);zone(s,t,m,state);if(now<p.cooldown_until)fail(`Nouvel essai dans ${Math.ceil((p.cooldown_until-now)/1000)} s.`,409);
   if(b.action==='open'){p.opened_at??=now;result={ok:true};}
   else if(b.action==='hint'){if(p.hints>=m.hints.length)fail('Tous les indices ont été utilisés.');p.hints++;result={hint:m.hints[p.hints-1],points:missionPoints(c,p.hints)};}
   else if(b.action==='skip'){p.status='skipped';p.points=0;p.completed_at=now;result={correct:true,skipped:true,explanation:m.explanation};}
   else if(b.action==='answer'){const answer=str(b.answer,500);if(m.answers.some(v=>normalize(v)===normalize(answer))){p.status='solved';p.points=missionPoints(c,p.hints);p.completed_at=now;result={correct:true,points:p.points,explanation:m.explanation};}else{p.errors++;p.cooldown_until=now+15000;result={correct:false,cooldown_until:p.cooldown_until};}}
   else fail('Action inconnue.');
  });await event(db,s,t,b.action,`${m.name}${b.action==='answer'?result.correct?' · réponse juste':' · réponse fausse (+15 s)':''}`);return j(result)
 }
 if(action==='finale'&&r.method==='POST'){
  if(!t)fail('Reprends ton équipe.',401);running(s);const b=await body(r),now=Date.now();let result:any={};await mutate(db,t,state=>{if(state.progress.some(v=>v.status==='pending'))fail('Rassemble les six fragments avant la finale.');if(state.final_status==='solved')fail('Finale déjà résolue.',409);if(now<state.final_cooldown)fail('Attends la fin des 15 secondes.',409);if(normalize(str(b.answer,500))===normalize(c.finale.answer)){state.final_status='solved';state.final_points=c.finale.points;state.finished_at=now;state.elapsed_ms=Math.max(0,now-s.started_at-s.paused_ms);result={correct:true,explanation:c.finale.explanation}}else{state.final_errors++;state.final_cooldown=now+15000;result={correct:false,cooldown_until:state.final_cooldown}}});await event(db,s,t,'finale',result.correct?'Rituel réussi.':'Rituel incorrect (+15 s).');return j(result)
 }
 if(action==='intervention'&&r.method==='POST'){
  if(!admin)fail('Accès maître de jeu requis.',403);const b=await body(r),row=await one(db,'SELECT * FROM r_teams WHERE id = ? AND session_id = ?',b.team,s.id);if(!row)fail('Équipe inconnue.');const m=c.missions.find(v=>v.id===b.mission);if(!m)fail('Épreuve inconnue.');if(!['validate','bypass','reset'].includes(b.action))fail('Intervention inconnue.');if(b.action==='reset'&&s.mode!=='screen')fail('La remise à zéro est réservée aux sessions sur écran.');await mutate(db,row,state=>{const p=state.progress.find(v=>v.mission_id===m.id)!;if(b.action==='bypass'){if(!state.bypass.includes(m.id))state.bypass.push(m.id)}else if(b.action==='reset'){Object.assign(p,initial(c).progress.find(v=>v.mission_id===m.id));state.final_status='pending';state.final_points=0;state.finished_at=null;state.elapsed_ms=undefined}else{p.status='solved';p.points=missionPoints(c,p.hints);p.completed_at=Date.now();p.cooldown_until=0}});await event(db,s,row,'intervention',`${b.action} · ${m.name}`);return j({ok:true})
 }
 if(action==='messages'&&r.method==='POST'){
  if(!t&&!admin)fail('Rejoins une équipe pour écrire.',401);const b=await body(r),channel=admin&&b.channel==='all'?'all':'team',target=admin?(b.team||t?.id||null):t.id;if(channel==='team'&&!(await one(db,'SELECT id FROM r_teams WHERE id = ? AND session_id = ?',target,s.id)))fail('Choisis une équipe.');await stmt(db,'INSERT INTO r_messages (id,session_id,team_id,channel,author,body,created_at) VALUES (?,?,?,?,?,?,?)',uid(),s.id,channel==='all'?null:target,channel,admin&&(b.channel!==undefined||b.team!==undefined||!t)?'Maître de jeu':t.name,str(b.body,1000),Date.now()).run();return j({ok:true})
 }
 if(action==='photos'&&r.method==='POST'){
  if(!t)fail('Reprends ton équipe.',401);running(s);if(!env.BUCKET)fail('Le stockage des photos est indisponible.',503);if(Number(r.headers.get('Content-Length')||0)>2200000)fail('Photo trop lourde (2 Mo maximum).',413);
  const f=await r.formData(),file=f.get('file'),mission=c.missions.find(m=>m.id===f.get('mission'));if(!(file instanceof File)||!mission)fail('Photo ou épreuve manquante.');if(file.size>2000000||!['image/jpeg','image/png','image/webp'].includes(file.type))fail('Envoie une photo JPEG, PNG ou WebP de moins de 2 Mo.');
  const state:State=parse(t.state);if(state.progress.find(p=>p.mission_id===mission.id)?.status==='pending')fail('Obtiens la relique avant son défi photo.');if(await one(db,'SELECT id FROM r_photos WHERE team_id = ? AND mission_id = ?',t.id,mission.id))fail('Une photo a déjà été envoyée pour cette épreuve.');
  const bytes=await file.arrayBuffer(),u=new Uint8Array(bytes),magic=file.type==='image/jpeg'?u[0]===255&&u[1]===216:file.type==='image/png'?u[0]===137&&u[1]===80&&u[2]===78:u[0]===82&&u[1]===73&&u[8]===87&&u[9]===69;if(!magic)fail('Image invalide.');const id=uid(),key=`reliquaire/${s.id}/${t.id}/${id}`,caption=String(f.get('caption')||'').slice(0,300);
  await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:file.type}});try{await stmt(db,'INSERT INTO r_photos (id,session_id,team_id,mission_id,object_key,caption,created_at) VALUES (?,?,?,?,?,?,?)',id,s.id,t.id,mission.id,key,caption,Date.now()).run()}catch(e){await env.BUCKET.delete(key);throw e}await event(db,s,t,'photo',mission.name);return j({id},201)
 }
 const photoMatch=action.match(/^photos\/([a-z0-9-]+)$/i);
 if(photoMatch&&r.method==='GET'){const p=await one(db,'SELECT * FROM r_photos WHERE id = ? AND session_id = ?',photoMatch[1],s.id);if(!p||(!admin&&(!t||(p.team_id!==t.id&&s.status!=='ended'))))fail('Photo inaccessible.',403);const object=await env.BUCKET?.get(p.object_key);if(!object)fail('Photo introuvable.',404);return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'image/jpeg','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}})}
 if(action==='review'&&r.method==='POST'){if(!admin)fail('Accès maître de jeu requis.',403);const b=await body(r),p=await one(db,'SELECT * FROM r_photos WHERE id = ? AND session_id = ?',b.photo,s.id);if(!p)fail('Photo introuvable.');const m=c.missions.find(v=>v.id===p.mission_id)!;const points=Math.floor(num(b.points,0,m.bonusPoints));await stmt(db,'UPDATE r_photos SET reviewed = 1, points = ? WHERE id = ?',points,p.id).run();await event(db,s,{id:p.team_id},'bonus',`${m.name} · ${points} points`);return j({ok:true})}
 if(action==='export'&&r.method==='GET'){if(!admin)fail('Accès maître de jeu requis.',403);const response=await snapshot(r,env,s),data=await response.json();data.locations=await all(db,'SELECT team_id,lat,lng,accuracy,created_at FROM r_locations WHERE session_id = ? ORDER BY created_at',s.id);data.events=await all(db,'SELECT team_id,kind,detail,created_at FROM r_events WHERE session_id = ? ORDER BY created_at',s.id);return j(data)}
 if(action==='tracks'&&r.method==='GET'){if(!admin)fail('Accès maître de jeu requis.',403);return j({locations:await all(db,'SELECT team_id,lat,lng,accuracy,created_at FROM r_locations WHERE session_id = ? ORDER BY created_at DESC LIMIT 10000',s.id)})}
 fail('Adresse ou méthode inconnue.',404);
 }catch(e){if(e instanceof Failure)return j({error:e.message},e.status);console.error('Reliquaire API error',e);return j({error:'La sauvegarde est indisponible. Réessaie dans un instant.'},503)}}
