import type {Campaign,Mission} from "./types";
const source=(slug:string)=>`https://www.parisladefense.com/fr/territoire/oeuvres-art/${slug}`;
const m=(v:Partial<Mission>&Pick<Mission,"id"|"name"|"title"|"relic"|"symbol"|"lat"|"lng"|"story"|"history"|"question"|"answers"|"hints"|"explanation"|"bonus">):Mission=>({radius:75,minutes:8,source:source(v.id),options:[],bonusPoints:30,...v});
export const campaign:Campaign={title:"Les six sceaux de La Défense",intro:"Une archiviste a disparu. Son dernier dossier affirme que six œuvres protègent la dalle d'une présence ancienne. Retrouvez leurs sceaux dans l'ordre que vous choisissez. Les archives occultes sont fictives ; l'histoire des lieux est réelle.",duration:120,points:100,hintPenalty:20,missions:[
m({id:"arche",name:"Grande Arche",title:"La Porte",relic:"Le seuil",symbol:"◇",lat:48.893056,lng:2.236389,radius:100,minutes:6,source:"https://www.parisladefense.com/fr/territoire/tours-batiments/grande-arche-la",story:"L'archive porte deux dates. La première ouvre une révolution, la seconde un passage. Leur distance dans le temps est la clé du seuil.",history:"La Grande Arche est inaugurée en 1989, année du bicentenaire de la Révolution française. Elle prolonge l'axe historique de Paris.",question:"Sur l'archive : 1789 et 1989. Combien d'années les séparent ?",answers:["200","200 ans"],hints:["Soustrayez la date la plus ancienne à la plus récente.","1989 − 1789 = deux siècles."],explanation:"1989 − 1789 = 200. Vous récupérez le seuil ◇.",bonus:"Selfie de l'équipe : une personne semble tenir la Grande Arche entre ses doigts, sans grimper sur le mobilier."}),
m({id:"pouce",name:"Le Pouce de César",title:"L'Empreinte",relic:"L'empreinte",symbol:"✦",lat:48.893611,lng:2.238611,radius:65,minutes:7,story:"Une main gigantesque a laissé une trace dans le dossier. L'archiviste écrit : « Ce n'est pas la taille qui compte, mais le changement d'échelle. »",history:"Le Pouce de César mesure 12 mètres. Le modèle original, moulage du pouce de l'artiste réalisé en 1965, mesurait 40 centimètres.",question:"De 40 cm à 12 m : par combien la hauteur a-t-elle été multipliée ?",answers:["30","x30","×30"],hints:["Convertissez les mètres en centimètres avant de diviser.","12 mètres font 1 200 cm. Divisez par 40."],explanation:"1 200 ÷ 40 = 30. L'empreinte ✦ rejoint votre carnet.",bonus:"Reproduisez le Pouce : chacun montre son pouce, avec une expression excessivement solennelle."}),
m({id:"agam",name:"Fontaine Agam",title:"Le Prisme",relic:"Le prisme",symbol:"△",lat:48.890556,lng:2.2425,minutes:9,source:source("fontaine-monumentale"),story:"Trois bandes colorées sont annotées : « Suivez l'ordre du spectre. La lumière est la serrure. » Un petit tableau accompagne cette phrase.",history:"La fontaine de Yaacov Agam associe eau, couleur et illusion de mouvement. Sa mosaïque possède 86 nuances d'émaux de Venise. L'épreuve ne nécessite pas que les jets fonctionnent.",question:"Le dossier donne : bleu 450 nm, vert 530 nm, rouge 650 nm. Classez ces couleurs de la plus petite à la plus grande longueur d'onde.",options:["Bleu, vert, rouge","Rouge, bleu, vert","Vert, rouge, bleu"],answers:["Bleu, vert, rouge"],hints:["Il suffit de ranger les trois nombres par ordre croissant.","450, puis 530, puis 650."],explanation:"Bleu → vert → rouge. Le prisme △ recompose la lumière. Ces valeurs simplifiées appartiennent au dossier de jeu.",bonus:"Photo de groupe : inventez une chorégraphie de fontaine, en restant sur le chemin piéton."}),
m({id:"statue",name:"La Défense de Paris",title:"Les Témoins",relic:"Le témoin",symbol:"○",lat:48.890278,lng:2.243056,radius:90,source:source("defense-paris"),story:"Trois témoignages fictifs : A — « Je suis la ville, debout sous un drapeau. » B — « Je suis le soldat, près de mon fusil. » C — « Je suis l'enfant : notre monument célèbre une bataille de 1914. » Un témoin falsifie l'archive.",history:"La Défense de Paris, de Louis-Ernest Barrias, date de 1883. Elle évoque la défense de Paris pendant la guerre de 1870 et a donné son nom au quartier. Ses figures représentent Paris, les défenseurs et la population civile.",question:"Quel témoignage contredit l'histoire du monument ?",options:["A — La ville","B — Le soldat","C — L'enfant"],answers:["C — L'enfant"],hints:["Comparez l'année du monument à celle de la bataille évoquée.","Un monument de 1883 ne commémore pas une bataille de 1914."],explanation:"C ment : l'œuvre concerne la guerre de 1870. Le témoin ○ atteste votre découverte.",bonus:"Photo de l'équipe en statues dramatiques : personne ne touche ni n'escalade l'œuvre."}),
m({id:"moretti",name:"Le Moretti",title:"Le Souffle",relic:"Le souffle",symbol:"≋",lat:48.889041,lng:2.247849,radius:90,minutes:10,story:"Sous les couleurs, quelque chose respire. L'archive cache le mot LHNY YEX (ignorez l'espace). Alphabet : A B C D E F G H I J K L M N O P Q R S T U V W X Y Z. Reculez de 19 positions, en bouclant après A. Exemple : L devient S.",history:"Le Moretti habille une cheminée d'aération de 32 mètres avec 672 tubes en fibre de verre, peints de 19 couleurs différentes.",question:"Déchiffrez le mot du dossier en reculant chaque lettre de 19 positions.",answers:["souffle"],hints:["Reculer de 19 revient à avancer de 7 dans un alphabet de 26 lettres. L devient S.","Les trois premières lettres du mot sont S, O, U."],explanation:"SOUFFLE. Le souffle ≋ relie les espaces cachés à la surface.",bonus:"Pose de groupe en tubes multicolores : bras tendus vers le ciel, sans bloquer le passage."}),
m({id:"takis",name:"Bassin Takis",title:"Les Signaux",relic:"Le signal",symbol:"⊙",lat:48.888056,lng:2.250278,radius:85,minutes:10,source:source("bassin"),story:"Le carnet retranscrit trois pulsations : ··· / −−− / ···. Son lexique indique S = ···, O = −−−, T = −. La présence réclame-t-elle de l'aide, ou est-ce un piège ?",history:"Le bassin Takis rassemble 49 signaux lumineux aux formes géométriques colorées. Inspiré par la lumière, le mouvement et les champs magnétiques, Takis marque ainsi une extrémité de l'axe.",question:"Avec le lexique fourni, que signifie ··· / −−− / ··· ?",answers:["sos","s o s"],hints:["Les barres obliques séparent les trois lettres.","La première et la dernière lettre sont S."],explanation:"SOS. Le signal ⊙ rejoint vos découvertes. Aucune lumière allumée n'est nécessaire pour lire le document fictif.",bonus:"Photo de l'équipe lançant un SOS théâtral vers Paris, depuis le chemin piéton."})
],finale:{question:"Le dernier dossier dit : « Le seuil contient le passage ; les cinq autres fragments l'alimentent. » Quel geste referme la brèche ?",options:["Placer le seuil autour des cinq autres fragments","Détruire le seuil et réunir les autres fragments","Éloigner tous les fragments les uns des autres"],answer:"Placer le seuil autour des cinq autres fragments",explanation:"Le seuil ◇ contient les cinq autres fragments. La brèche se referme. L'archiviste a laissé un dernier mot : « Le quartier peut enfin dormir. »",points:200}};
const moretti=campaign.missions.find(m=>m.id==="moretti")!;
const cipher="SOUFFLE".split("").map(c=>String.fromCharCode(65+(c.charCodeAt(0)-65+19)%26)).join("");
moretti.story=`Sous les couleurs, quelque chose respire. L'archiviste a chiffré un mot : ${cipher}. Alphabet : A B C D E F G H I J K L M N O P Q R S T U V W X Y Z. Pour retrouver chaque lettre, reculez de 19 positions en bouclant après A. Exemple : L devient S.`;
moretti.question=`Reculez chaque lettre de ${cipher} de 19 positions dans l'alphabet. Quel mot apparaît ?`;
